
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class VentanaCrudEst extends javax.swing.JInternalFrame {
    
    public VentanaCrudEst() {
        initComponents();
        // this.setLocation(-100, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnAgregar = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblAsignarDoc = new javax.swing.JLabel();
        cmbAsignarDoc = new javax.swing.JComboBox<>();
        lblLogo = new javax.swing.JLabel();
        jpnBotonesCrud = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(470, 307));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnAgregar.setBackground(new java.awt.Color(181, 199, 211));
        jpnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        jpnAgregar.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        lblPassword.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblPassword.setText("Contraseña:");
        jpnAgregar.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblCorreo.setText("Correo:");
        jpnAgregar.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        txtNombre.setEditable(false);
        jpnAgregar.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 70, 380, -1));
        jpnAgregar.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 110, 380, -1));
        jpnAgregar.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 150, 380, -1));

        lblTitulo.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agregar Estudiante");
        jpnAgregar.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 200, -1));

        lblAsignarDoc.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblAsignarDoc.setText("Docente:");
        jpnAgregar.add(lblAsignarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        cmbAsignarDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbAsignarDoc.setKeySelectionManager(null);
        jpnAgregar.add(cmbAsignarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 190, 380, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/book.png"))); // NOI18N
        lblLogo.setText("jLabel1");
        jpnAgregar.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 80, -1));

        getContentPane().add(jpnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 533, 264));

        jpnBotonesCrud.setBackground(new java.awt.Color(181, 199, 211));
        jpnBotonesCrud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setBackground(new java.awt.Color(181, 199, 211));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/beige.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jpnBotonesCrud.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 30));
        btnModificar.getAccessibleContext().setAccessibleParent(jpnBotonesCrud);

        btnAgregar.setBackground(new java.awt.Color(181, 199, 211));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/green.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpnBotonesCrud.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 30));

        btnCancelar.setBackground(new java.awt.Color(181, 199, 211));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/white.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jpnBotonesCrud.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 90, 30));

        btnEliminar.setBackground(new java.awt.Color(181, 199, 211));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/red.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpnBotonesCrud.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 30));

        getContentPane().add(jpnBotonesCrud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 533, 50));

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        /*this.setVisible(false);
        this.getTextFieldCorreo().setText("");
        this.getTextFieldNombre().setText("");
        this.getTextFieldPassword().setText("");*/
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        /*this.setVisible(false);
        this.getTextFieldCorreo().setText("");
        this.getTextFieldNombre().setText("");
        this.getTextFieldPassword().setText("");*/
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        /*this.setVisible(false);
        this.getTextFieldCorreo().setText("");
        this.getTextFieldNombre().setText("");
        this.getTextFieldPassword().setText("");*/
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        /*this.setVisible(false);
        this.getTextFieldCorreo().setText("");
        this.getTextFieldNombre().setText("");
        this.getTextFieldPassword().setText("");*/
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbAsignarDoc;
    private javax.swing.JPanel jpnAgregar;
    private javax.swing.JPanel jpnBotonesCrud;
    private javax.swing.JLabel lblAsignarDoc;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JTextField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public JComboBox<String> getCmbAsignarDoc() {
        return cmbAsignarDoc;
    }

    public void setCmbAsignarDoc(JComboBox<String> cmbAsignarDoc) {
        this.cmbAsignarDoc = cmbAsignarDoc;
    }
    
}
