
package vista;

import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class VentanaEstudiante extends javax.swing.JFrame {
    private VentanaObservacion ventanaObservacion;
    private boolean asistencia = false;
    private boolean observacion = false;
    
    public VentanaEstudiante() {
        initComponents();
        this.setLocationRelativeTo(null);
        ventanaObservacion = new VentanaObservacion();
        ventanaObservacion.setVisible(false);
        
        JInternalFrame jif = new JInternalFrame();
        jif.setVisible(false);
        
        this.desktopPanel.add(ventanaObservacion);
        this.desktopPanel.add(jif);
        
        JInternalFrame jif2 = new JInternalFrame();
        jif2.setVisible(false);
        this.desktopPanel.add(jif2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        desktopPanel = new javax.swing.JDesktopPane();
        jpnTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpnCrud = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblBarraBaja = new javax.swing.JLabel();
        jpnOpciones = new javax.swing.JPanel();
        btnAsistencias = new javax.swing.JButton();
        btnObservaciones = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jpnDatos = new javax.swing.JPanel();
        scpTabla = new javax.swing.JScrollPane();
        tblInicio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudiante");
        setResizable(false);

        desktopPanel.setLayout(new java.awt.BorderLayout());

        jpnTitulo.setBackground(new java.awt.Color(164, 234, 190));
        jpnTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Estudiante");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitulo.setPreferredSize(new java.awt.Dimension(800, 60));
        jpnTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/estudiante.png"))); // NOI18N
        jpnTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        desktopPanel.add(jpnTitulo, java.awt.BorderLayout.PAGE_START);

        jpnCrud.setBackground(new java.awt.Color(164, 234, 190));
        jpnCrud.setPreferredSize(new java.awt.Dimension(750, 70));
        jpnCrud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(164, 234, 190));
        btnSalir.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/white.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPreferredSize(new java.awt.Dimension(90, 30));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpnCrud.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        lblBarraBaja.setBackground(new java.awt.Color(0, 0, 0));
        lblBarraBaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarraBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        lblBarraBaja.setText("jLabel1");
        jpnCrud.add(lblBarraBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 850, 20));

        desktopPanel.add(jpnCrud, java.awt.BorderLayout.PAGE_END);

        jpnOpciones.setBackground(new java.awt.Color(164, 234, 190));
        jpnOpciones.setPreferredSize(new java.awt.Dimension(160, 300));
        java.awt.GridBagLayout panelOpcionesLayout = new java.awt.GridBagLayout();
        panelOpcionesLayout.columnWidths = new int[] {0};
        panelOpcionesLayout.rowHeights = new int[] {0, 15, 0, 15, 0};
        jpnOpciones.setLayout(panelOpcionesLayout);

        btnAsistencias.setBackground(new java.awt.Color(164, 234, 190));
        btnAsistencias.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        btnAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonEstudiante.png"))); // NOI18N
        btnAsistencias.setText("Ver Asistencias");
        btnAsistencias.setBorder(null);
        btnAsistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistencias.setFocusPainted(false);
        btnAsistencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsistencias.setPreferredSize(new java.awt.Dimension(150, 40));
        btnAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jpnOpciones.add(btnAsistencias, gridBagConstraints);

        btnObservaciones.setBackground(new java.awt.Color(164, 234, 190));
        btnObservaciones.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        btnObservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonEstudiante.png"))); // NOI18N
        btnObservaciones.setText("Ver Observaciones");
        btnObservaciones.setBorder(null);
        btnObservaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObservaciones.setFocusPainted(false);
        btnObservaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnObservaciones.setPreferredSize(new java.awt.Dimension(150, 40));
        btnObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObservacionesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jpnOpciones.add(btnObservaciones, gridBagConstraints);

        btnInicio.setBackground(new java.awt.Color(164, 234, 190));
        btnInicio.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonEstudiante.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setPreferredSize(new java.awt.Dimension(150, 40));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jpnOpciones.add(btnInicio, gridBagConstraints);

        desktopPanel.add(jpnOpciones, java.awt.BorderLayout.LINE_START);

        jpnDatos.setBackground(new java.awt.Color(164, 234, 190));
        jpnDatos.setPreferredSize(new java.awt.Dimension(660, 290));

        tblInicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scpTabla.setViewportView(tblInicio);

        javax.swing.GroupLayout jpnDatosLayout = new javax.swing.GroupLayout(jpnDatos);
        jpnDatos.setLayout(jpnDatosLayout);
        jpnDatosLayout.setHorizontalGroup(
            jpnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDatosLayout.createSequentialGroup()
                .addComponent(scpTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jpnDatosLayout.setVerticalGroup(
            jpnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        desktopPanel.add(jpnDatos, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObservacionesActionPerformed
        // TODO add your handling code here:
        this.btnSalir.setVisible(false);
        
        this.lblTitulo.setText("Observaciones");
        this.lblTitulo.setPreferredSize(new Dimension(800, 60));
        
        this.asistencia = false;
        this.observacion = true;
        
        this.tblInicio.setCursor(new Cursor(12));
    }//GEN-LAST:event_btnObservacionesActionPerformed

    private void btnAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciasActionPerformed
        // TODO add your handling code here:
        this.btnSalir.setVisible(false);
        
        this.lblTitulo.setText("Asistencias");
        this.lblTitulo.setPreferredSize(new Dimension(800, 60));
        this.lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        this.asistencia = true;
        this.observacion = false;
        
        this.tblInicio.setCursor(new Cursor(0));
    }//GEN-LAST:event_btnAsistenciasActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        this.btnSalir.setVisible(true);
        this.tblInicio.setModel(new DefaultTableModel());
        
        // this.lblTitulo.setText("Bienvenido Estudiante");
        this.lblTitulo.setPreferredSize(new Dimension(800, 60));
        
        this.asistencia = false;
        this.observacion = false;
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:

        // Ocultar ventana actual
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnObservaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpnCrud;
    private javax.swing.JPanel jpnDatos;
    private javax.swing.JPanel jpnOpciones;
    private javax.swing.JPanel jpnTitulo;
    private javax.swing.JLabel lblBarraBaja;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scpTabla;
    private javax.swing.JTable tblInicio;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAsistencias() {
        return btnAsistencias;
    }

    public JButton getBtnInicio() {
        return btnInicio;
    }

    public JButton getBtnObservaciones() {
        return btnObservaciones;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public JTable getTblInicio() {
        return tblInicio;
    }

    public void setTblInicio(JTable tblIncio) {
        this.tblInicio = tblIncio;
    }

    public VentanaObservacion getVentanaObservacion() {
        return ventanaObservacion;
    }

    public void setVentanaObservacion(VentanaObservacion ventanaObservacion) {
        this.ventanaObservacion = ventanaObservacion;
    }

    public boolean isAsistencia() {
        return asistencia;
    }

    public void setAsistencia(boolean asistencia) {
        this.asistencia = asistencia;
    }

    public boolean isObservacion() {
        return observacion;
    }

    public void setObservacion(boolean observacion) {
        this.observacion = observacion;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }
    
    
    
}
