package vista;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class VentanaAdmin extends javax.swing.JFrame {
    private VentanaCrudDoc ventanaCrudDoc;
    private VentanaCrudEst ventanaCrudEst;
    private boolean registrarDocente;
    private boolean registrarEstudiante;
    
    // private boolean btnRegistrarEstu;
    // private boolean btnSalir;
    //private JTable tablaInicio;

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ventanaCrudDoc = new VentanaCrudDoc();
        // ventanaCrudDoc.setBounds(-100, 0, 469, 307);
        // ventanaCrudDoc.setLocation(50, 50);
        ventanaCrudDoc.setVisible(false);
        
        // ventanaCrudDoc.pack();
        this.desktopPanel.add(ventanaCrudDoc);

        ventanaCrudEst = new VentanaCrudEst();
        ventanaCrudEst.setVisible(false);
        this.desktopPanel.add(ventanaCrudEst);
        
        JInternalFrame jif = new JInternalFrame();
        jif.setVisible(false);
        this.desktopPanel.add(jif);
        
        this.btnAgregar.setVisible(false);
        this.btnModificar.setVisible(false);
        this.btnEliminar.setVisible(false);
        this.btnHabilitarUser.setVisible(false);
        this.btnDeshabilitar.setVisible(false);

        /*tablaInicio = new JTable();
        tablaInicio.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Edad", "Identificacion", "Correo", "Telefono"
                }
        ));*/
    }

    public void modificarTabla(DefaultTableModel modelo) {
        this.tblInicio.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new javax.swing.JDesktopPane();
        jpnTitulo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jpnCrud = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnHabilitarUser = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();
        lblBarraBaja = new javax.swing.JLabel();
        jpnOpciones = new javax.swing.JPanel();
        btnRegistrarDoc = new javax.swing.JButton();
        btnRegistrarEstu = new javax.swing.JButton();
        btnHabilitar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jpnDatos = new javax.swing.JPanel();
        scpTabla = new javax.swing.JScrollPane();
        tblInicio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);

        desktopPanel.setBackground(new java.awt.Color(242, 242, 242));
        desktopPanel.setPreferredSize(new java.awt.Dimension(850, 450));
        desktopPanel.setLayout(new java.awt.BorderLayout());

        jpnTitulo.setBackground(new java.awt.Color(181, 199, 211));
        jpnTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logoF (1).png"))); // NOI18N
        lblLogo.setText("jLabel1");
        jpnTitulo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 60));

        lblTitulo.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Administrador");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitulo.setPreferredSize(new java.awt.Dimension(150, 60));
        jpnTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 270, -1));

        desktopPanel.add(jpnTitulo, java.awt.BorderLayout.PAGE_START);

        jpnCrud.setBackground(new java.awt.Color(181, 199, 211));
        jpnCrud.setPreferredSize(new java.awt.Dimension(750, 80));
        jpnCrud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(181, 199, 211));
        btnSalir.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/white.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPreferredSize(new java.awt.Dimension(90, 30));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpnCrud.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 120, 30));

        btnAgregar.setBackground(new java.awt.Color(181, 199, 211));
        btnAgregar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/green.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.setFocusPainted(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpnCrud.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        btnModificar.setBackground(new java.awt.Color(181, 199, 211));
        btnModificar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/beige.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificar.setFocusPainted(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jpnCrud.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 90, -1));

        btnEliminar.setBackground(new java.awt.Color(181, 199, 211));
        btnEliminar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/red.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPreferredSize(new java.awt.Dimension(90, 30));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpnCrud.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 100, 30));

        btnHabilitarUser.setBackground(new java.awt.Color(181, 199, 211));
        btnHabilitarUser.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnHabilitarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/green.png"))); // NOI18N
        btnHabilitarUser.setText("Habilitar");
        btnHabilitarUser.setBorder(null);
        btnHabilitarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHabilitarUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHabilitarUser.setPreferredSize(new java.awt.Dimension(105, 30));
        btnHabilitarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarUserActionPerformed(evt);
            }
        });
        jpnCrud.add(btnHabilitarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, -1));

        btnDeshabilitar.setBackground(new java.awt.Color(181, 199, 211));
        btnDeshabilitar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnDeshabilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/red.png"))); // NOI18N
        btnDeshabilitar.setText("Deshabilitar");
        btnDeshabilitar.setBorder(null);
        btnDeshabilitar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeshabilitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeshabilitar.setPreferredSize(new java.awt.Dimension(105, 30));
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });
        jpnCrud.add(btnDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 110, -1));

        lblBarraBaja.setBackground(new java.awt.Color(0, 0, 0));
        lblBarraBaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarraBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        lblBarraBaja.setText("jLabel1");
        jpnCrud.add(lblBarraBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 850, 20));

        desktopPanel.add(jpnCrud, java.awt.BorderLayout.PAGE_END);

        jpnOpciones.setBackground(new java.awt.Color(181, 199, 211));
        jpnOpciones.setPreferredSize(new java.awt.Dimension(180, 300));
        jpnOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarDoc.setBackground(new java.awt.Color(181, 199, 211));
        btnRegistrarDoc.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnRegistrarDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue.png"))); // NOI18N
        btnRegistrarDoc.setText("Registrar Docente");
        btnRegistrarDoc.setBorder(null);
        btnRegistrarDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarDoc.setFocusPainted(false);
        btnRegistrarDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarDoc.setPreferredSize(new java.awt.Dimension(155, 30));
        btnRegistrarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDocActionPerformed(evt);
            }
        });
        jpnOpciones.add(btnRegistrarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 40));

        btnRegistrarEstu.setBackground(new java.awt.Color(181, 199, 211));
        btnRegistrarEstu.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnRegistrarEstu.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEstu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue.png"))); // NOI18N
        btnRegistrarEstu.setText("Registrar Estudiante");
        btnRegistrarEstu.setBorder(null);
        btnRegistrarEstu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarEstu.setFocusPainted(false);
        btnRegistrarEstu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarEstu.setPreferredSize(new java.awt.Dimension(155, 30));
        btnRegistrarEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEstuActionPerformed(evt);
            }
        });
        jpnOpciones.add(btnRegistrarEstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 40));

        btnHabilitar.setBackground(new java.awt.Color(181, 199, 211));
        btnHabilitar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnHabilitar.setForeground(new java.awt.Color(255, 255, 255));
        btnHabilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue.png"))); // NOI18N
        btnHabilitar.setText("Habilitar Usuario");
        btnHabilitar.setBorder(null);
        btnHabilitar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHabilitar.setFocusPainted(false);
        btnHabilitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHabilitar.setPreferredSize(new java.awt.Dimension(155, 30));
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });
        jpnOpciones.add(btnHabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 40));

        btnInicio.setBackground(new java.awt.Color(181, 199, 211));
        btnInicio.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setPreferredSize(new java.awt.Dimension(100, 30));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jpnOpciones.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 40));

        desktopPanel.add(jpnOpciones, java.awt.BorderLayout.LINE_START);

        jpnDatos.setBackground(new java.awt.Color(181, 199, 211));
        jpnDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scpTabla.setBackground(new java.awt.Color(243, 246, 251));
        scpTabla.setBorder(null);
        scpTabla.setOpaque(false);

        tblInicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scpTabla.setViewportView(tblInicio);

        jpnDatos.add(scpTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 643, 300));

        desktopPanel.add(jpnDatos, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        desktopPanel.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEstuActionPerformed
        // TODO add your handling code here:
        this.btnSalir.setVisible(false);
        this.btnHabilitarUser.setVisible(false);
        this.btnDeshabilitar.setVisible(false);

        this.btnAgregar.setVisible(true);
        this.btnModificar.setVisible(true);
        this.btnEliminar.setVisible(true);

        this.lblTitulo.setText("Registrar Estudiante");
        this.lblTitulo.setPreferredSize(new Dimension(220, 60));
        
        this.registrarDocente = false;
        this.registrarEstudiante = true;
    }//GEN-LAST:event_btnRegistrarEstuActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        // Ocultar ventana actual
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDocActionPerformed
        // TODO add your handling code here:
        this.btnSalir.setVisible(false);
        this.btnHabilitarUser.setVisible(false);
        this.btnDeshabilitar.setVisible(false);

        this.btnAgregar.setVisible(true);
        this.btnModificar.setVisible(true);
        this.btnEliminar.setVisible(true);

        this.lblTitulo.setText("Registrar Docente");
        this.lblTitulo.setPreferredSize(new Dimension(200, 60));
        
        this.registrarDocente = true;
        this.registrarEstudiante = false;
    }//GEN-LAST:event_btnRegistrarDocActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        this.btnSalir.setVisible(true);

        this.btnAgregar.setVisible(false);
        this.btnModificar.setVisible(false);
        this.btnEliminar.setVisible(false);
        this.btnHabilitarUser.setVisible(false);
        this.btnDeshabilitar.setVisible(false);

        this.lblTitulo.setText("Administrador");
        this.lblTitulo.setPreferredSize(new Dimension(150, 60));
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
        // TODO add your handling code here:
        this.btnSalir.setVisible(false);
        this.btnAgregar.setVisible(false);
        this.btnModificar.setVisible(false);
        this.btnEliminar.setVisible(false);

        this.btnHabilitarUser.setVisible(true);
        this.btnDeshabilitar.setVisible(true);

        this.lblTitulo.setText("Habilitar Usuario");
        this.lblTitulo.setPreferredSize(new Dimension(200, 60));
    }//GEN-LAST:event_btnHabilitarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(registrarDocente){
            // ventanaCrudDoc.setVisible(true);
            ventanaCrudDoc.getLblTitulo().setText("Agregar Docente");
            ventanaCrudDoc.getBtnAgregar().setVisible(true);
            ventanaCrudDoc.getBtnEliminar().setVisible(false);
            ventanaCrudDoc.getBtnModificar().setVisible(false);
            // ventanaCrudDoc.dispose();
        } else if(registrarEstudiante){
            // ventanaCrudEst.setVisible(true);
            ventanaCrudEst.getLblTitulo().setText("Agregar Estudiante");
            ventanaCrudEst.getBtnAgregar().setVisible(true);
            ventanaCrudEst.getBtnEliminar().setVisible(false);
            ventanaCrudEst.getBtnModificar().setVisible(false);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(registrarDocente){
            // ventanaCrudDoc.setVisible(true);
            ventanaCrudDoc.getLblTitulo().setText("Modificar Docente");
            ventanaCrudDoc.getBtnAgregar().setVisible(false);
            ventanaCrudDoc.getBtnEliminar().setVisible(false);
            ventanaCrudDoc.getBtnModificar().setVisible(true);
            // ventanaCrudDoc.dispose();
        } else if(registrarEstudiante){
            // ventanaCrudEst.setVisible(true);
            ventanaCrudEst.getLblTitulo().setText("Modificar Estudiante");
            ventanaCrudEst.getBtnAgregar().setVisible(false);
            ventanaCrudEst.getBtnEliminar().setVisible(false);
            ventanaCrudEst.getBtnModificar().setVisible(true);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(registrarDocente){
            // ventanaCrudDoc.setVisible(true);
            ventanaCrudDoc.getLblTitulo().setText("Eliminar Docente");
            ventanaCrudDoc.getBtnAgregar().setVisible(false);
            ventanaCrudDoc.getBtnEliminar().setVisible(true);
            ventanaCrudDoc.getBtnModificar().setVisible(false);
            // ventanaCrudDoc.dispose();
        } else if(registrarEstudiante){
            // ventanaCrudEst.setVisible(true);
            ventanaCrudEst.getLblTitulo().setText("Eliminar Estudiante");
            ventanaCrudEst.getBtnAgregar().setVisible(false);
            ventanaCrudEst.getBtnEliminar().setVisible(true);
            ventanaCrudEst.getBtnModificar().setVisible(false);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeshabilitarActionPerformed

    private void btnHabilitarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHabilitarUserActionPerformed

    // Tipos:
    // 1. Ningún error  X
    // 2. Error ventanaCrudDoc  X
    // 3. Error ventanaCrudEst  X
    public void mostrarDatos(String mensaje/*, int tipo*/){
        JOptionPane.showMessageDialog(null, mensaje);
        /*switch(tipo){
            case 2 -> this.ventanaCrudDoc.setVisible(false);
            case 3 -> this.ventanaCrudEst.setVisible(false);
        }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JButton btnHabilitarUser;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrarDoc;
    private javax.swing.JButton btnRegistrarEstu;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JPanel jpnCrud;
    private javax.swing.JPanel jpnDatos;
    private javax.swing.JPanel jpnOpciones;
    private javax.swing.JPanel jpnTitulo;
    private javax.swing.JLabel lblBarraBaja;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scpTabla;
    private javax.swing.JTable tblInicio;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnDeshabilitar() {
        return btnDeshabilitar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnHabilitar() {
        return btnHabilitar;
    }

    public JButton getBtnHabilitarUser() {
        return btnHabilitarUser;
    }

    public JButton getBtnInicio() {
        return btnInicio;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JButton getBtnRegistrarDoc() {
        return btnRegistrarDoc;
    }

    public JButton getBtnRegistrarEstu() {
        return btnRegistrarEstu;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public JTable getTblInicio() {
        return tblInicio;
    }

    public boolean isRegistrarDocente() {
        return registrarDocente;
    }

    public boolean isRegistrarEstudiante() {
        return registrarEstudiante;
    }

    public VentanaCrudDoc getVentanaCrudDoc() {
        return ventanaCrudDoc;
    }

    public VentanaCrudEst getVentanaCrudEst() {
        return ventanaCrudEst;
    }
    
    
}
