package vista;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.*;

public class VentanaInicio extends javax.swing.JFrame {

    public VentanaInicio() {
        initComponents();
        txtUsuario.setForeground(Color.GRAY);
        txtUsuario.setText("Usuario");
        txtUsuario.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtUsuario.getText().equals("Usuario")) {
                    txtUsuario.setText("");
                    txtUsuario.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txtUsuario.getText().isEmpty()) {
                    txtUsuario.setForeground(Color.GRAY);
                    txtUsuario.setText("Usuario");
                }
            }
        });
        pwdUsuario.setForeground(Color.GRAY);
        pwdUsuario.setEchoChar((char) 0); 
        pwdUsuario.setText("Contraseña");
        // pwdUsuario.setBorder();
        pwdUsuario.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                char[] password = pwdUsuario.getPassword();
                String passwordText = new String(password);
                if (passwordText.equals("Contraseña")) {
                    pwdUsuario.setText("");
                    pwdUsuario.setForeground(Color.BLACK);
                    pwdUsuario.setEchoChar('\u2022');
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                char[] password = pwdUsuario.getPassword();
                String passwordText = new String(password);
                if (passwordText.isEmpty()) {
                    pwdUsuario.setForeground(Color.GRAY);
                    pwdUsuario.setText("Contraseña");
                    pwdUsuario.setEchoChar((char) 0); // Mostrar el texto ingresado sin ocultarlo
                }
            }
        });
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnInicio = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pwdUsuario = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        cmbRoles = new javax.swing.JComboBox<>();
        lblUserIcon = new javax.swing.JLabel();
        lblBarraBaja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de asistencia y observaciones");

        jpnInicio.setBackground(new java.awt.Color(250, 251, 253));
        jpnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblTitulo.setText("Inicio de sesión");
        jpnInicio.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 160, -1));

        txtUsuario.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtUsuario.setPreferredSize(new java.awt.Dimension(64, 27));
        jpnInicio.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 170, 30));

        pwdUsuario.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        pwdUsuario.setToolTipText("");
        pwdUsuario.setPreferredSize(new java.awt.Dimension(64, 27));
        pwdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdUsuarioActionPerformed(evt);
            }
        });
        jpnInicio.add(pwdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 170, 30));

        btnIngresar.setBackground(new java.awt.Color(250, 251, 253));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/entrar_1.png"))); // NOI18N
        btnIngresar.setBorder(null);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setFocusPainted(false);
        btnIngresar.setPreferredSize(new java.awt.Dimension(85, 30));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        btnIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIngresarKeyPressed(evt);
            }
        });
        jpnInicio.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 30, 40));

        cmbRoles.setBackground(new java.awt.Color(250, 251, 253));
        cmbRoles.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cmbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rol", "Administrador", "Docente", "Estudiante" }));
        cmbRoles.setBorder(null);
        cmbRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbRoles.setKeySelectionManager(null);
        cmbRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolesActionPerformed(evt);
            }
        });
        jpnInicio.add(cmbRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 170, 30));

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/user_3.png"))); // NOI18N
        jpnInicio.add(lblUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, -1));

        lblBarraBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo.jpg"))); // NOI18N
        lblBarraBaja.setText("jLabel1");
        jpnInicio.add(lblBarraBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 400, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        this.getTxtUsuario().setText("");
        this.getPwdUsuario().setText("");
        txtUsuario.setForeground(Color.GRAY);
        txtUsuario.setText("Usuario");
        
        pwdUsuario.setForeground(Color.GRAY);
        pwdUsuario.setEchoChar((char) 0); 
        pwdUsuario.setText("Contraseña");
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIngresarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarKeyPressed

    private void cmbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cmbRoles;
    private javax.swing.JPanel jpnInicio;
    private javax.swing.JLabel lblBarraBaja;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JPasswordField pwdUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void mostrarDatos(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    public JButton getBtnIngresar() {
        return btnIngresar;
    }

    public JComboBox<String> getCmbRoles() {
        return cmbRoles;
    }

    public JPasswordField getPwdUsuario() {
        return pwdUsuario;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

}
