/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;

/**
 *
 * @author st147
 */
public class VentanaCargarFecha extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCargarFecha
     */
    public VentanaCargarFecha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jpnFecha = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        fTxtFecha = new javax.swing.JFormattedTextField();
        lblFormatoFecha = new javax.swing.JLabel();
        jpnBotones = new javax.swing.JPanel();
        btnCargar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jpnTitulo.setBackground(new java.awt.Color(181, 199, 211));
        jpnTitulo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Buscar por fecha:");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpnTitulo.add(lblTitulo, java.awt.BorderLayout.CENTER);

        jpnFecha.setBackground(new java.awt.Color(181, 199, 211));
        jpnFecha.setLayout(new java.awt.GridBagLayout());

        lblFecha.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblFecha.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 55, 0, 0);
        jpnFecha.add(lblFecha, gridBagConstraints);

        try {
            fTxtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtFecha.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 0, 119);
        jpnFecha.add(fTxtFecha, gridBagConstraints);

        lblFormatoFecha.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblFormatoFecha.setText("AAAA/MM/DD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 20, 0);
        jpnFecha.add(lblFormatoFecha, gridBagConstraints);

        jpnBotones.setBackground(new java.awt.Color(181, 199, 211));
        jpnBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargar.setBackground(new java.awt.Color(181, 199, 211));
        btnCargar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/green.png"))); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.setBorder(null);
        btnCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargar.setFocusPainted(false);
        btnCargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCargar.setPreferredSize(new java.awt.Dimension(80, 30));
        jpnBotones.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 5, 100, 30));

        btnCancelar.setBackground(new java.awt.Color(181, 199, 211));
        btnCancelar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/white.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setPreferredSize(new java.awt.Dimension(90, 30));
        jpnBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 5, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JFormattedTextField fTxtFecha;
    private javax.swing.JPanel jpnBotones;
    private javax.swing.JPanel jpnFecha;
    private javax.swing.JPanel jpnTitulo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFormatoFecha;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnCargar() {
        return btnCargar;
    }

    public void setBtnCargar(JButton btnCargar) {
        this.btnCargar = btnCargar;
    }

    public JFormattedTextField getfTxtFecha() {
        return fTxtFecha;
    }

    public void setfTxtFecha(JFormattedTextField fTxtFecha) {
        this.fTxtFecha = fTxtFecha;
    }
    
}
