/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author st147
 */
public class VentanaCrudObservacion extends javax.swing.JInternalFrame {
    // private boolean agregar = false;
    // private boolean modificar = false;
    // private boolean eliminar = false;
    /**
     * Creates new form VentanaCrudObservacion
     */
    public VentanaCrudObservacion() {
        initComponents();
    }

    /*public void cambiarInfoCrud(int tipo){
        switch(tipo){
            case 1:
                
                agregar = true;
                modificar = false;
                eliminar = false;
                
                break;
                
            case 2:
                agregar = false;
                modificar = true;
                eliminar = false;
                
                break;
            
            case 3:
                agregar = false;
                modificar = false;
                eliminar = true;
                
                break;
        }
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jpnObservacion = new javax.swing.JPanel();
        scpObservacion = new javax.swing.JScrollPane();
        txtaObservacion = new javax.swing.JTextArea();
        lblEstudiante = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jpnBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(470, 370));

        jpnTitulo.setBackground(new java.awt.Color(181, 199, 211));
        jpnTitulo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agregar Observación");
        jpnTitulo.add(lblTitulo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpnTitulo, java.awt.BorderLayout.PAGE_START);

        jpnObservacion.setBackground(new java.awt.Color(181, 199, 211));
        jpnObservacion.setPreferredSize(new java.awt.Dimension(308, 270));

        txtaObservacion.setColumns(20);
        txtaObservacion.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtaObservacion.setLineWrap(true);
        txtaObservacion.setRows(5);
        scpObservacion.setViewportView(txtaObservacion);

        lblEstudiante.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblEstudiante.setText("Estudiante:");

        lblNombre.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpnObservacionLayout = new javax.swing.GroupLayout(jpnObservacion);
        jpnObservacion.setLayout(jpnObservacionLayout);
        jpnObservacionLayout.setHorizontalGroup(
            jpnObservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnObservacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnObservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addGroup(jpnObservacionLayout.createSequentialGroup()
                        .addComponent(lblEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnObservacionLayout.setVerticalGroup(
            jpnObservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnObservacionLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jpnObservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudiante)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addComponent(scpObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jpnObservacion, java.awt.BorderLayout.CENTER);

        jpnBotones.setBackground(new java.awt.Color(181, 199, 211));
        java.awt.GridBagLayout panelBotonesLayout = new java.awt.GridBagLayout();
        panelBotonesLayout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0};
        panelBotonesLayout.rowHeights = new int[] {0};
        jpnBotones.setLayout(panelBotonesLayout);

        btnAgregar.setBackground(new java.awt.Color(181, 199, 211));
        btnAgregar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/green.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setFocusPainted(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jpnBotones.add(btnAgregar, gridBagConstraints);

        btnCancelar.setBackground(new java.awt.Color(181, 199, 211));
        btnCancelar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/white.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setPreferredSize(new java.awt.Dimension(85, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jpnBotones.add(btnCancelar, gridBagConstraints);

        btnModificar.setBackground(new java.awt.Color(181, 199, 211));
        btnModificar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/beige.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setFocusPainted(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPreferredSize(new java.awt.Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jpnBotones.add(btnModificar, gridBagConstraints);

        btnEliminar.setBackground(new java.awt.Color(181, 199, 211));
        btnEliminar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/red.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPreferredSize(new java.awt.Dimension(85, 30));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jpnBotones.add(btnEliminar, gridBagConstraints);

        getContentPane().add(jpnBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jpnBotones;
    private javax.swing.JPanel jpnObservacion;
    private javax.swing.JPanel jpnTitulo;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scpObservacion;
    private javax.swing.JTextArea txtaObservacion;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public void setBtnModificar(JButton btnModificar) {
        this.btnModificar = btnModificar;
    }

    public JLabel getLabelTitulo() {
        return lblTitulo;
    }

    public void setLabelTitulo(JLabel labelTitulo) {
        this.lblTitulo = labelTitulo;
    }

    public JTextArea getTxtaObservacion() {
        return txtaObservacion;
    }

    public void setTxtaObservacion(JTextArea txtaObservacion) {
        this.txtaObservacion = txtaObservacion;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    

    
}
